# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: aeb67e1f
    url: /
    weight: 10
  - name: Papers
    identifier: d9f0a5cc
    url: /#papers
    weight: 20
  - name: Talks
    identifier: d64180b4
    url: /#talks
    weight: 30
  - name: News
    identifier: e2235b37
    url: /#news
    weight: 40
  - name: Experience
    identifier: 4702c7f4
    url: experience/
    weight: 50
  - name: Projects
    identifier: c6e6920a
    url: projects/
    weight: 60
