# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: aeb67e1f
    url: /
    weight: 10
  - name: Papers
    identifier: d9f0a5cc
    url: /publications/
    weight: 20
  - name: CV
    identifier: 4702c7f4
    url: /cv/
    weight: 30
