hugoblox:
  schema: "2.0"
  identity:
    name: "Dr. Lorenzo Lamberti"
    type: person
    tagline: Postdoc | ETH Zurich, IDSIA
    description: Lorenzo Lamberti is an AI and robotics researcher at ETH Zürich, and IDSIA.
    organization: ETH Zurich, IDSIA USI-SUPSI
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: true
    toc:
      enable: true
    reading_time:
      enable: true
    citations:
      style: ieee
  search:
    enable: true
  seo:
    title: Lorenzo Lamberti | Postdoc | ETH Zurich, IDSIA USI-SUPSI
